import { ADD, CLICK, CONDITION, DISPLAY, FUNCTIONED, RELOAD, ROUTER, SERVER, ZOOM } from "./Library/Functions/Connection.js";

window.ADD=ADD;
window.CONDITION=CONDITION;
window.DISPLAY=DISPLAY;
window.FUNCTIONED=FUNCTIONED;
window.ROUTER=ROUTER;
window.CLICK=CLICK;
window.SERVER=SERVER;
window.RELOAD=RELOAD;
window.ZOOM=ZOOM;